before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - build_release
  - deploy
  - remove

build:
  tags:
    - develop
  only:
    - develop
  stage: build
  script:
    - export APP_URL=https://$CI_PROJECT_NAME-$CI_COMMIT_BRANCH.gitlab.designcopilot.io
    - docker compose -f docker-compose.develop.yml build

build_release:
  tags:
    - develop
  only:
    - main
  stage: build
  script:
    - export APP_URL=https://$CI_PROJECT_NAME-$CI_COMMIT_BRANCH.gitlab.designcopilot.io
    - docker compose -f docker-compose.develop.yml build
    - docker compose -f docker-compose.develop.yml push

deploy:
  tags:
    - develop
  only:
    - develop
  stage: deploy
  script:
    - docker compose -f docker-compose.develop.yml up -d --force-recreate

remove:
  tags:
    - develop
  only:
    - develop
  stage: remove
  script:
    - docker compose -f docker-compose.develop.yml stop
  when: manual
